/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package JohannaGutierrezTesting;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
    
public static int[] ordenar(int[] A) {
		
		if(A.length==0) {
			System.out.println("No hay elementos en el arreglo");
			return null;
		}
				
        int i, j, aux;
        for (i = 0; i < A.length - 1; i++) {
            for (j = 0; j < A.length - i - 1; j++) {                                                              
                if (A[j + 1] < A[j]) {
                    aux = A[j + 1];
                    A[j + 1] = A[j];
                    A[j] = aux;
                }
            }
        }
        
        return A;


	}
}
